// Custom scrub bar with hover-thumbnail previews (in-webview player only).
//
// Sits just above the native `<video controls>`. It mirrors the video's
// current time / duration, lets the user click/drag to seek, and on hover shows
// a thumbnail tooltip (generated by useScrubThumbnails) above the bar at the
// hovered position with a time label. The native controls keep play/pause/volume
// /fullscreen; this bar adds the scrub preview the native bar can't.
//
// Gated to the in-webview path by the parent (the external mpv/VLC panel never
// renders this). Performance: the preview generation is throttled + cached in
// the hook; this component only does cheap pointer math.

import { useCallback, useRef, useState } from "react";
import type { ScrubPreview } from "./useScrubThumbnails";

/** Format seconds as M:SS or H:MM:SS. */
export function formatTime(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds < 0) return "0:00";
  const s = Math.floor(seconds % 60);
  const m = Math.floor((seconds / 60) % 60);
  const h = Math.floor(seconds / 3600);
  const ss = String(s).padStart(2, "0");
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${ss}`;
  return `${m}:${ss}`;
}

interface ScrubBarProps {
  currentTime: number;
  duration: number;
  preview: ScrubPreview | null;
  onHover: (timeSeconds: number) => void;
  onLeave: () => void;
  onSeek: (timeSeconds: number) => void;
  /** Lets a parent suppress transient overlays while a pointer seek is active. */
  onScrubbingChange?: (scrubbing: boolean) => void;
}

export function ScrubBar({
  currentTime,
  duration,
  preview,
  onHover,
  onLeave,
  onSeek,
  onScrubbingChange,
}: ScrubBarProps) {
  const barRef = useRef<HTMLDivElement | null>(null);
  const [hoverX, setHoverX] = useState<number | null>(null);

  const timeAtX = useCallback(
    (clientX: number): { time: number; ratio: number } | null => {
      const bar = barRef.current;
      if (bar == null || !Number.isFinite(duration) || duration <= 0) return null;
      const rect = bar.getBoundingClientRect();
      const ratio = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
      return { time: ratio * duration, ratio };
    },
    [duration],
  );

  const handleMove = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      const at = timeAtX(e.clientX);
      if (at == null) return;
      const rect = barRef.current!.getBoundingClientRect();
      setHoverX(e.clientX - rect.left);
      onHover(at.time);
    },
    [timeAtX, onHover],
  );

  const handleLeave = useCallback(() => {
    setHoverX(null);
    onLeave();
    onScrubbingChange?.(false);
  }, [onLeave, onScrubbingChange]);

  const handleClick = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      const at = timeAtX(e.clientX);
      if (at != null) onSeek(at.time);
    },
    [timeAtX, onSeek],
  );

  // Keyboard seeking - a role="slider" must respond to arrows/Home/End (WCAG
  // 2.1). Arrows nudge ±5s, PageUp/Down ±60s, Home/End jump to the ends.
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLDivElement>) => {
      if (!Number.isFinite(duration) || duration <= 0) return;
      const STEP = 5;
      const BIG = 60;
      let next: number | null = null;
      switch (e.key) {
        case "ArrowRight":
        case "ArrowUp":
          next = currentTime + STEP;
          break;
        case "ArrowLeft":
        case "ArrowDown":
          next = currentTime - STEP;
          break;
        case "PageUp":
          next = currentTime + BIG;
          break;
        case "PageDown":
          next = currentTime - BIG;
          break;
        case "Home":
          next = 0;
          break;
        case "End":
          next = duration;
          break;
        default:
          return;
      }
      e.preventDefault();
      onSeek(Math.max(0, Math.min(duration, next)));
    },
    [currentTime, duration, onSeek],
  );

  const progress =
    Number.isFinite(duration) && duration > 0
      ? Math.max(0, Math.min(1, currentTime / duration))
      : 0;

  const showTooltip = hoverX != null && preview != null;

  return (
    <div className="scrubbar-wrap">
      {showTooltip && (
        <div
          className="scrub-tooltip glass-raised glass-lit"
          style={{ left: `${hoverX}px` }}
        >
          {preview.image ? (
            <img
              className="scrub-thumb"
              src={preview.image}
              alt=""
              draggable={false}
            />
          ) : (
            <div className="scrub-thumb scrub-thumb-empty" />
          )}
          <span className="scrub-time">{formatTime(preview.time)}</span>
        </div>
      )}
      <div
        ref={barRef}
        className="scrubbar"
        onPointerMove={handleMove}
        onPointerLeave={handleLeave}
        onPointerDown={(event) => {
          onScrubbingChange?.(true);
          handleClick(event);
        }}
        onPointerUp={() => onScrubbingChange?.(false)}
        onPointerCancel={() => onScrubbingChange?.(false)}
        onKeyDown={handleKeyDown}
        role="slider"
        aria-label="Seek"
        aria-valuemin={0}
        aria-valuemax={Number.isFinite(duration) ? Math.floor(duration) : 0}
        aria-valuenow={Math.floor(currentTime)}
        aria-valuetext={formatTime(currentTime)}
        tabIndex={0}
      >
        <div className="scrubbar-track">
          <div
            className="scrubbar-fill"
            style={{ width: `${progress * 100}%` }}
          />
          {hoverX != null && (
            <div className="scrubbar-hover" style={{ left: `${hoverX}px` }} />
          )}
        </div>
      </div>
    </div>
  );
}
