#!/usr/bin/env node
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const serverEntry = join(root, "server", "dist", "index.cjs");
const webDist = join(root, "web", "dist");
const webIndex = join(webDist, "index.html");
const dest = join(root, "web", "src-tauri", "resources", "server");

function requirePath(path, hint) {
  if (!existsSync(path)) {
    console.error(`Missing ${relative(root, path)}.`);
    console.error(hint);
    process.exit(1);
  }
}

requirePath(serverEntry, "Run `cd server && npm run build` first.");
requirePath(webIndex, "Run `cd web && npm run build` first.");

rmSync(dest, { recursive: true, force: true });
mkdirSync(dest, { recursive: true });
writeFileSync(join(dest, ".gitignore"), "*\n!.gitignore\n!README.md\n");
writeFileSync(
  join(dest, "README.md"),
  "Generated desktop-server resources are written here during release prep.\n\n" +
    "Run `node scripts/prepare_tauri_server_resources.mjs` after building `server/`\n" +
    "and `web/`. The generated files are ignored by git.\n",
);

cpSync(serverEntry, join(dest, "index.cjs"));
cpSync(webDist, join(dest, "web-dist"), { recursive: true });
writeFileSync(
  join(dest, "manifest.json"),
  JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      serverEntry: "index.cjs",
      webDist: "web-dist",
      note: "Generated by scripts/prepare_tauri_server_resources.mjs.",
    },
    null,
    2,
  ),
);

console.log(`Prepared Tauri server resources in ${relative(root, dest)}.`);
