#!/usr/bin/env node
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = process.cwd();
const serverEntry = join(root, "server", "dist", "index.cjs");
const webDist = join(root, "web", "dist");
const webIndex = join(webDist, "index.html");
const dest = join(root, "web", "src-tauri", "resources", "server");

function requirePath(path, hint) {
  if (!existsSync(path)) {
    console.error(`Missing ${relative(root, path)}.`);
    console.error(hint);
    process.exit(1);
  }
}

requirePath(serverEntry, "Run `cd server && npm run build` first.");
requirePath(webIndex, "Run `cd web && npm run build` first.");

mkdirSync(dest, { recursive: true });
rmSync(join(dest, "index.cjs"), { force: true });
rmSync(join(dest, "web-dist"), { recursive: true, force: true });
rmSync(join(dest, "manifest.json"), { force: true });

cpSync(serverEntry, join(dest, "index.cjs"));
cpSync(webDist, join(dest, "web-dist"), { recursive: true });
writeFileSync(
  join(dest, "manifest.json"),
  JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      serverEntry: "index.cjs",
      webDist: "web-dist",
      note: "Generated by scripts/prepare_tauri_server_resources.mjs.",
    },
    null,
    2,
  ),
);

console.log(`Prepared Tauri server resources in ${relative(root, dest)}.`);
